// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fitniqakjeqsxsdamema.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZpdG5pcWFramVxc3hzZGFtZW1hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkwODEzMzEsImV4cCI6MjA1NDY1NzMzMX0.yIXwd-WmrxxHAJsfKd6qH2TfqssrkAn3lZDJoQBiLBw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);